<?php

namespace Acme\FmpsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonRepository extends EntityRepository
{
    public function findBySearchCriteria($options, $user = null)
    {

      $qb = $this->createQueryBuilder('b')->select('b');

			$ecoles = $user->getEcoles();

		  if ($user && !empty($ecoles) && !in_array(1, $ecoles))
			{
					$qb->andWhere($qb->expr()->in('b.ecoleId', $ecoles));
			}
      
      if ($options->getEcole() && $options->getEcole() != '')
      {
          $qb->andWhere('b.ecoleId = :ecole_id')->setParameter('ecole_id', $options->getEcole()); 
      }

			if ($options->getBudget() && $options->getBudget() != '')
      {
          $qb->andWhere('b.budgetId = :b_id')->setParameter('b_id', $options->getBudget()); 
      }
      
      if ($options->getFournisseur() && $options->getFournisseur() != '')
      {
          $qb->andWhere('b.fournisseur = :f')->setParameter('f', $options->getFournisseur());
      }
     
      if ($options->getPatente() && $options->getPatente() != '')
      {
          $qb->andWhere('b.patente = :patente')->setParameter('patente', $options->getPatente());
      }
      
      return $qb->getQuery();
    }
}
