<?php

namespace Acme\FmpsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DechargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DechargeRepository extends EntityRepository
{
    
     public function findBySearchCriteria($options, $user = null)
    {

      $qb = $this->createQueryBuilder('d')->select('d');

			$ecoles = $user->getEcoles();

		  if ($user && !empty($ecoles) && !in_array(1, $ecoles))
			{
					$qb->andWhere($qb->expr()->in('d.ecoleId', $ecoles));
			}
      
      if ($options->getEcole() && $options->getEcole() != '')
      {
          $qb->andWhere('d.ecoleId = :ecole_id')->setParameter('ecole_id', $options->getEcole()); 
      }

			if ($options->getBudget() && $options->getBudget() != '')
      {
          $qb->andWhere('d.budgetId = :b_id')->setParameter('b_id', $options->getBudget()); 
      }
      
      if ($options->getNom() && $options->getNom() != '')
      {
          $qb->andWhere('d.nom = :nom')->setParameter('nom', $options->getNom());
      }
     
      if ($options->getPrenom() && $options->getPrenom() != '')
      {
          $qb->andWhere('d.prenom = :prenom')->setParameter('prenom', $options->getPrenom());
      }
      if ($options->getCin() && $options->getCin() != '')
      {
          $qb->andWhere('d.cin = :cin')->setParameter('cin', $options->getCin());
      }
       
       
      return $qb->getQuery();
    }
}
