parameters:
#    acme_fmps.example.class: Acme\FmpsBundle\Example

services:
#    acme_fmps.example:
#        class: %acme_fmps.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     acme_user.registration.form.type:
         class: Acme\FmpsBundle\Form\Type\RegistrationFormType
         arguments: [%fos_user.model.user.class%]
         tags:
             - { name: form.type, alias: acme_user_registration }
                                          
     acme_fmps.inscription.postPersist :
         class: Acme\FmpsBundle\Listener\InscriptionListener
         tags:
             - { name: doctrine.event_listener, event: postPersist, alias: acme_fmps_inscription }    